all: loopcpu loopsys mytimes

loopcpu: loopcpu.c
		gcc -Wall -o loopcpu loopcpu.c

loopsys: loopsys.c
		gcc -Wall -o loopsys loopsys.c

mytimes : lance_commande.c
		gcc -Wall -o mytimes lance_commande.c
